name: Scheduled Job

on:
  schedule:
    - cron: '* * * * *'   # Runs every  minute

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run script
        run: echo "Running scheduled job..."
