name: Scheduled Job

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run script
        run: echo "Running scheduled job..."
